# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from racecar_cone_msgs/ConePair.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import racecar_cone_msgs.msg
import std_msgs.msg

class ConePair(genpy.Message):
  _md5sum = "e86328cf0c5c9f6e1d43796e78dbb005"
  _type = "racecar_cone_msgs/ConePair"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header
racecar_cone_msgs/Cone left
racecar_cone_msgs/Cone right
geometry_msgs/Point midpoint
float32 width                   # ||right - left||

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: racecar_cone_msgs/Cone
# Detección de un cono (frame fijo: odom/map)
std_msgs/Header header
geometry_msgs/Point p           # posición (z=0 si 2D)
# Covarianza plana 2x2 (x,y) aplanada (row-major): [xx, xy, yx, yy]
float32[4] cov_xy

# Lateralidad
uint8 UNKNOWN=0
uint8 LEFT=1
uint8 RIGHT=2
uint8 side

float32 confidence              # [0..1]
string source                   # "lidar", "sim", etc.
int32 id                        # opcional (tracking)

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['header','left','right','midpoint','width']
  _slot_types = ['std_msgs/Header','racecar_cone_msgs/Cone','racecar_cone_msgs/Cone','geometry_msgs/Point','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,left,right,midpoint,width

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ConePair, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.left is None:
        self.left = racecar_cone_msgs.msg.Cone()
      if self.right is None:
        self.right = racecar_cone_msgs.msg.Cone()
      if self.midpoint is None:
        self.midpoint = geometry_msgs.msg.Point()
      if self.width is None:
        self.width = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.left = racecar_cone_msgs.msg.Cone()
      self.right = racecar_cone_msgs.msg.Cone()
      self.midpoint = geometry_msgs.msg.Point()
      self.width = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.left.header.seq, _x.left.header.stamp.secs, _x.left.header.stamp.nsecs))
      _x = self.left.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3d().pack(_x.left.p.x, _x.left.p.y, _x.left.p.z))
      buff.write(_get_struct_4f().pack(*self.left.cov_xy))
      _x = self
      buff.write(_get_struct_Bf().pack(_x.left.side, _x.left.confidence))
      _x = self.left.source
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_i3I().pack(_x.left.id, _x.right.header.seq, _x.right.header.stamp.secs, _x.right.header.stamp.nsecs))
      _x = self.right.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3d().pack(_x.right.p.x, _x.right.p.y, _x.right.p.z))
      buff.write(_get_struct_4f().pack(*self.right.cov_xy))
      _x = self
      buff.write(_get_struct_Bf().pack(_x.right.side, _x.right.confidence))
      _x = self.right.source
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_i3df().pack(_x.right.id, _x.midpoint.x, _x.midpoint.y, _x.midpoint.z, _x.width))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.left is None:
        self.left = racecar_cone_msgs.msg.Cone()
      if self.right is None:
        self.right = racecar_cone_msgs.msg.Cone()
      if self.midpoint is None:
        self.midpoint = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.left.header.seq, _x.left.header.stamp.secs, _x.left.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.left.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.left.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 24
      (_x.left.p.x, _x.left.p.y, _x.left.p.z,) = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 16
      self.left.cov_xy = _get_struct_4f().unpack(str[start:end])
      _x = self
      start = end
      end += 5
      (_x.left.side, _x.left.confidence,) = _get_struct_Bf().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.left.source = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.left.source = str[start:end]
      _x = self
      start = end
      end += 16
      (_x.left.id, _x.right.header.seq, _x.right.header.stamp.secs, _x.right.header.stamp.nsecs,) = _get_struct_i3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.right.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.right.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 24
      (_x.right.p.x, _x.right.p.y, _x.right.p.z,) = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 16
      self.right.cov_xy = _get_struct_4f().unpack(str[start:end])
      _x = self
      start = end
      end += 5
      (_x.right.side, _x.right.confidence,) = _get_struct_Bf().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.right.source = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.right.source = str[start:end]
      _x = self
      start = end
      end += 32
      (_x.right.id, _x.midpoint.x, _x.midpoint.y, _x.midpoint.z, _x.width,) = _get_struct_i3df().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.left.header.seq, _x.left.header.stamp.secs, _x.left.header.stamp.nsecs))
      _x = self.left.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3d().pack(_x.left.p.x, _x.left.p.y, _x.left.p.z))
      buff.write(self.left.cov_xy.tostring())
      _x = self
      buff.write(_get_struct_Bf().pack(_x.left.side, _x.left.confidence))
      _x = self.left.source
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_i3I().pack(_x.left.id, _x.right.header.seq, _x.right.header.stamp.secs, _x.right.header.stamp.nsecs))
      _x = self.right.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3d().pack(_x.right.p.x, _x.right.p.y, _x.right.p.z))
      buff.write(self.right.cov_xy.tostring())
      _x = self
      buff.write(_get_struct_Bf().pack(_x.right.side, _x.right.confidence))
      _x = self.right.source
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_i3df().pack(_x.right.id, _x.midpoint.x, _x.midpoint.y, _x.midpoint.z, _x.width))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.left is None:
        self.left = racecar_cone_msgs.msg.Cone()
      if self.right is None:
        self.right = racecar_cone_msgs.msg.Cone()
      if self.midpoint is None:
        self.midpoint = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.left.header.seq, _x.left.header.stamp.secs, _x.left.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.left.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.left.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 24
      (_x.left.p.x, _x.left.p.y, _x.left.p.z,) = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 16
      self.left.cov_xy = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=4)
      _x = self
      start = end
      end += 5
      (_x.left.side, _x.left.confidence,) = _get_struct_Bf().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.left.source = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.left.source = str[start:end]
      _x = self
      start = end
      end += 16
      (_x.left.id, _x.right.header.seq, _x.right.header.stamp.secs, _x.right.header.stamp.nsecs,) = _get_struct_i3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.right.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.right.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 24
      (_x.right.p.x, _x.right.p.y, _x.right.p.z,) = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 16
      self.right.cov_xy = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=4)
      _x = self
      start = end
      end += 5
      (_x.right.side, _x.right.confidence,) = _get_struct_Bf().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.right.source = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.right.source = str[start:end]
      _x = self
      start = end
      end += 32
      (_x.right.id, _x.midpoint.x, _x.midpoint.y, _x.midpoint.z, _x.width,) = _get_struct_i3df().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_4f = None
def _get_struct_4f():
    global _struct_4f
    if _struct_4f is None:
        _struct_4f = struct.Struct("<4f")
    return _struct_4f
_struct_Bf = None
def _get_struct_Bf():
    global _struct_Bf
    if _struct_Bf is None:
        _struct_Bf = struct.Struct("<Bf")
    return _struct_Bf
_struct_i3I = None
def _get_struct_i3I():
    global _struct_i3I
    if _struct_i3I is None:
        _struct_i3I = struct.Struct("<i3I")
    return _struct_i3I
_struct_i3df = None
def _get_struct_i3df():
    global _struct_i3df
    if _struct_i3df is None:
        _struct_i3df = struct.Struct("<i3df")
    return _struct_i3df
