# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from racecar_cone_msgs/TrackMetrics.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class TrackMetrics(genpy.Message):
  _md5sum = "9f81acf08fbcb042f5be8a05aaee3bf6"
  _type = "racecar_cone_msgs/TrackMetrics"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header

# Cobertura de emparejado (0..1)
float32 coverage

# Estadística de anchos
float32 std_width                      # desviación estándar de width (m)

# Curvatura y suavidad
float32 max_kappa                      # max |kappa| (1/m)
float32 integral_kappa_sq              # ∫ kappa^2 ds (1/m)

# Rendimiento
float32 latency_ms                     # latencia media del ciclo (ms)

# Contadores
uint32 cones_raw_count
uint32 pairs_count
uint32 midpoints_count

# Notas/diagnóstico
string notes

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','coverage','std_width','max_kappa','integral_kappa_sq','latency_ms','cones_raw_count','pairs_count','midpoints_count','notes']
  _slot_types = ['std_msgs/Header','float32','float32','float32','float32','float32','uint32','uint32','uint32','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,coverage,std_width,max_kappa,integral_kappa_sq,latency_ms,cones_raw_count,pairs_count,midpoints_count,notes

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TrackMetrics, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.coverage is None:
        self.coverage = 0.
      if self.std_width is None:
        self.std_width = 0.
      if self.max_kappa is None:
        self.max_kappa = 0.
      if self.integral_kappa_sq is None:
        self.integral_kappa_sq = 0.
      if self.latency_ms is None:
        self.latency_ms = 0.
      if self.cones_raw_count is None:
        self.cones_raw_count = 0
      if self.pairs_count is None:
        self.pairs_count = 0
      if self.midpoints_count is None:
        self.midpoints_count = 0
      if self.notes is None:
        self.notes = ''
    else:
      self.header = std_msgs.msg.Header()
      self.coverage = 0.
      self.std_width = 0.
      self.max_kappa = 0.
      self.integral_kappa_sq = 0.
      self.latency_ms = 0.
      self.cones_raw_count = 0
      self.pairs_count = 0
      self.midpoints_count = 0
      self.notes = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_5f3I().pack(_x.coverage, _x.std_width, _x.max_kappa, _x.integral_kappa_sq, _x.latency_ms, _x.cones_raw_count, _x.pairs_count, _x.midpoints_count))
      _x = self.notes
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 32
      (_x.coverage, _x.std_width, _x.max_kappa, _x.integral_kappa_sq, _x.latency_ms, _x.cones_raw_count, _x.pairs_count, _x.midpoints_count,) = _get_struct_5f3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.notes = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.notes = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_5f3I().pack(_x.coverage, _x.std_width, _x.max_kappa, _x.integral_kappa_sq, _x.latency_ms, _x.cones_raw_count, _x.pairs_count, _x.midpoints_count))
      _x = self.notes
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 32
      (_x.coverage, _x.std_width, _x.max_kappa, _x.integral_kappa_sq, _x.latency_ms, _x.cones_raw_count, _x.pairs_count, _x.midpoints_count,) = _get_struct_5f3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.notes = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.notes = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_5f3I = None
def _get_struct_5f3I():
    global _struct_5f3I
    if _struct_5f3I is None:
        _struct_5f3I = struct.Struct("<5f3I")
    return _struct_5f3I
