// Generated by gencpp from file racecar_cone_msgs/Centerline.msg
// DO NOT EDIT!


#ifndef RACECAR_CONE_MSGS_MESSAGE_CENTERLINE_H
#define RACECAR_CONE_MSGS_MESSAGE_CENTERLINE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace racecar_cone_msgs
{
template <class ContainerAllocator>
struct Centerline_
{
  typedef Centerline_<ContainerAllocator> Type;

  Centerline_()
    : header()
    , samples()
    , s()
    , kappa()
    , is_arclength_uniform(false)
    , ds(0.0)
    , ctrl_pts()  {
    }
  Centerline_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , samples(_alloc)
    , s(_alloc)
    , kappa(_alloc)
    , is_arclength_uniform(false)
    , ds(0.0)
    , ctrl_pts(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _samples_type;
  _samples_type samples;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _s_type;
  _s_type s;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _kappa_type;
  _kappa_type kappa;

   typedef uint8_t _is_arclength_uniform_type;
  _is_arclength_uniform_type is_arclength_uniform;

   typedef float _ds_type;
  _ds_type ds;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _ctrl_pts_type;
  _ctrl_pts_type ctrl_pts;





  typedef boost::shared_ptr< ::racecar_cone_msgs::Centerline_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::racecar_cone_msgs::Centerline_<ContainerAllocator> const> ConstPtr;

}; // struct Centerline_

typedef ::racecar_cone_msgs::Centerline_<std::allocator<void> > Centerline;

typedef boost::shared_ptr< ::racecar_cone_msgs::Centerline > CenterlinePtr;
typedef boost::shared_ptr< ::racecar_cone_msgs::Centerline const> CenterlineConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::racecar_cone_msgs::Centerline_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::racecar_cone_msgs::Centerline_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::racecar_cone_msgs::Centerline_<ContainerAllocator1> & lhs, const ::racecar_cone_msgs::Centerline_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.samples == rhs.samples &&
    lhs.s == rhs.s &&
    lhs.kappa == rhs.kappa &&
    lhs.is_arclength_uniform == rhs.is_arclength_uniform &&
    lhs.ds == rhs.ds &&
    lhs.ctrl_pts == rhs.ctrl_pts;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::racecar_cone_msgs::Centerline_<ContainerAllocator1> & lhs, const ::racecar_cone_msgs::Centerline_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace racecar_cone_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::racecar_cone_msgs::Centerline_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::racecar_cone_msgs::Centerline_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::racecar_cone_msgs::Centerline_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::racecar_cone_msgs::Centerline_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::racecar_cone_msgs::Centerline_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::racecar_cone_msgs::Centerline_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::racecar_cone_msgs::Centerline_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3934b303e0826c747777abfdd52e228c";
  }

  static const char* value(const ::racecar_cone_msgs::Centerline_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3934b303e0826c74ULL;
  static const uint64_t static_value2 = 0x7777abfdd52e228cULL;
};

template<class ContainerAllocator>
struct DataType< ::racecar_cone_msgs::Centerline_<ContainerAllocator> >
{
  static const char* value()
  {
    return "racecar_cone_msgs/Centerline";
  }

  static const char* value(const ::racecar_cone_msgs::Centerline_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::racecar_cone_msgs::Centerline_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header                 # frame_id típico: \"odom\"\n"
"\n"
"# Muestras de la trayectoria c(s) remuestreadas\n"
"geometry_msgs/Point[] samples          # tamaño N\n"
"\n"
"# Longitud de arco acumulada para cada sample (m)\n"
"float32[] s                            # tamaño N, s[0]=0\n"
"\n"
"# Curvatura por muestra (1/m). Signo según convención (yaw izquierda +)\n"
"float32[] kappa                        # tamaño N\n"
"\n"
"# Metadatos de muestreo\n"
"bool is_arclength_uniform              # true si s es uniforme\n"
"float32 ds                             # paso nominal en s (m), 0 si no aplica\n"
"\n"
"# (Opcional) puntos de control del ajuste (vacío si no aplica)\n"
"geometry_msgs/Point[] ctrl_pts\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::racecar_cone_msgs::Centerline_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::racecar_cone_msgs::Centerline_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.samples);
      stream.next(m.s);
      stream.next(m.kappa);
      stream.next(m.is_arclength_uniform);
      stream.next(m.ds);
      stream.next(m.ctrl_pts);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Centerline_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::racecar_cone_msgs::Centerline_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::racecar_cone_msgs::Centerline_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "samples[]" << std::endl;
    for (size_t i = 0; i < v.samples.size(); ++i)
    {
      s << indent << "  samples[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.samples[i]);
    }
    s << indent << "s[]" << std::endl;
    for (size_t i = 0; i < v.s.size(); ++i)
    {
      s << indent << "  s[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.s[i]);
    }
    s << indent << "kappa[]" << std::endl;
    for (size_t i = 0; i < v.kappa.size(); ++i)
    {
      s << indent << "  kappa[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.kappa[i]);
    }
    s << indent << "is_arclength_uniform: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_arclength_uniform);
    s << indent << "ds: ";
    Printer<float>::stream(s, indent + "  ", v.ds);
    s << indent << "ctrl_pts[]" << std::endl;
    for (size_t i = 0; i < v.ctrl_pts.size(); ++i)
    {
      s << indent << "  ctrl_pts[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.ctrl_pts[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RACECAR_CONE_MSGS_MESSAGE_CENTERLINE_H
