// Generated by gencpp from file racecar_cone_msgs/Cone.msg
// DO NOT EDIT!


#ifndef RACECAR_CONE_MSGS_MESSAGE_CONE_H
#define RACECAR_CONE_MSGS_MESSAGE_CONE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>

namespace racecar_cone_msgs
{
template <class ContainerAllocator>
struct Cone_
{
  typedef Cone_<ContainerAllocator> Type;

  Cone_()
    : header()
    , p()
    , cov_xy()
    , side(0)
    , confidence(0.0)
    , source()
    , id(0)  {
      cov_xy.assign(0.0);
  }
  Cone_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , p(_alloc)
    , cov_xy()
    , side(0)
    , confidence(0.0)
    , source(_alloc)
    , id(0)  {
  (void)_alloc;
      cov_xy.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _p_type;
  _p_type p;

   typedef boost::array<float, 4>  _cov_xy_type;
  _cov_xy_type cov_xy;

   typedef uint8_t _side_type;
  _side_type side;

   typedef float _confidence_type;
  _confidence_type confidence;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _source_type;
  _source_type source;

   typedef int32_t _id_type;
  _id_type id;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(UNKNOWN)
  #undef UNKNOWN
#endif
#if defined(_WIN32) && defined(LEFT)
  #undef LEFT
#endif
#if defined(_WIN32) && defined(RIGHT)
  #undef RIGHT
#endif

  enum {
    UNKNOWN = 0u,
    LEFT = 1u,
    RIGHT = 2u,
  };


  typedef boost::shared_ptr< ::racecar_cone_msgs::Cone_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::racecar_cone_msgs::Cone_<ContainerAllocator> const> ConstPtr;

}; // struct Cone_

typedef ::racecar_cone_msgs::Cone_<std::allocator<void> > Cone;

typedef boost::shared_ptr< ::racecar_cone_msgs::Cone > ConePtr;
typedef boost::shared_ptr< ::racecar_cone_msgs::Cone const> ConeConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::racecar_cone_msgs::Cone_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::racecar_cone_msgs::Cone_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::racecar_cone_msgs::Cone_<ContainerAllocator1> & lhs, const ::racecar_cone_msgs::Cone_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.p == rhs.p &&
    lhs.cov_xy == rhs.cov_xy &&
    lhs.side == rhs.side &&
    lhs.confidence == rhs.confidence &&
    lhs.source == rhs.source &&
    lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::racecar_cone_msgs::Cone_<ContainerAllocator1> & lhs, const ::racecar_cone_msgs::Cone_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace racecar_cone_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::racecar_cone_msgs::Cone_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::racecar_cone_msgs::Cone_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::racecar_cone_msgs::Cone_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::racecar_cone_msgs::Cone_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::racecar_cone_msgs::Cone_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::racecar_cone_msgs::Cone_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::racecar_cone_msgs::Cone_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ac79e60f67f210d41f97d0cd883ed6b5";
  }

  static const char* value(const ::racecar_cone_msgs::Cone_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xac79e60f67f210d4ULL;
  static const uint64_t static_value2 = 0x1f97d0cd883ed6b5ULL;
};

template<class ContainerAllocator>
struct DataType< ::racecar_cone_msgs::Cone_<ContainerAllocator> >
{
  static const char* value()
  {
    return "racecar_cone_msgs/Cone";
  }

  static const char* value(const ::racecar_cone_msgs::Cone_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::racecar_cone_msgs::Cone_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Detección de un cono (frame fijo: odom/map)\n"
"std_msgs/Header header\n"
"geometry_msgs/Point p           # posición (z=0 si 2D)\n"
"# Covarianza plana 2x2 (x,y) aplanada (row-major): [xx, xy, yx, yy]\n"
"float32[4] cov_xy\n"
"\n"
"# Lateralidad\n"
"uint8 UNKNOWN=0\n"
"uint8 LEFT=1\n"
"uint8 RIGHT=2\n"
"uint8 side\n"
"\n"
"float32 confidence              # [0..1]\n"
"string source                   # \"lidar\", \"sim\", etc.\n"
"int32 id                        # opcional (tracking)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::racecar_cone_msgs::Cone_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::racecar_cone_msgs::Cone_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.p);
      stream.next(m.cov_xy);
      stream.next(m.side);
      stream.next(m.confidence);
      stream.next(m.source);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Cone_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::racecar_cone_msgs::Cone_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::racecar_cone_msgs::Cone_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "p: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.p);
    s << indent << "cov_xy[]" << std::endl;
    for (size_t i = 0; i < v.cov_xy.size(); ++i)
    {
      s << indent << "  cov_xy[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.cov_xy[i]);
    }
    s << indent << "side: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.side);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
    s << indent << "source: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.source);
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RACECAR_CONE_MSGS_MESSAGE_CONE_H
