// Generated by gencpp from file racecar_cone_msgs/ConePair.msg
// DO NOT EDIT!


#ifndef RACECAR_CONE_MSGS_MESSAGE_CONEPAIR_H
#define RACECAR_CONE_MSGS_MESSAGE_CONEPAIR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <racecar_cone_msgs/Cone.h>
#include <racecar_cone_msgs/Cone.h>
#include <geometry_msgs/Point.h>

namespace racecar_cone_msgs
{
template <class ContainerAllocator>
struct ConePair_
{
  typedef ConePair_<ContainerAllocator> Type;

  ConePair_()
    : header()
    , left()
    , right()
    , midpoint()
    , width(0.0)  {
    }
  ConePair_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left(_alloc)
    , right(_alloc)
    , midpoint(_alloc)
    , width(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::racecar_cone_msgs::Cone_<ContainerAllocator>  _left_type;
  _left_type left;

   typedef  ::racecar_cone_msgs::Cone_<ContainerAllocator>  _right_type;
  _right_type right;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _midpoint_type;
  _midpoint_type midpoint;

   typedef float _width_type;
  _width_type width;





  typedef boost::shared_ptr< ::racecar_cone_msgs::ConePair_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::racecar_cone_msgs::ConePair_<ContainerAllocator> const> ConstPtr;

}; // struct ConePair_

typedef ::racecar_cone_msgs::ConePair_<std::allocator<void> > ConePair;

typedef boost::shared_ptr< ::racecar_cone_msgs::ConePair > ConePairPtr;
typedef boost::shared_ptr< ::racecar_cone_msgs::ConePair const> ConePairConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::racecar_cone_msgs::ConePair_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::racecar_cone_msgs::ConePair_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::racecar_cone_msgs::ConePair_<ContainerAllocator1> & lhs, const ::racecar_cone_msgs::ConePair_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.left == rhs.left &&
    lhs.right == rhs.right &&
    lhs.midpoint == rhs.midpoint &&
    lhs.width == rhs.width;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::racecar_cone_msgs::ConePair_<ContainerAllocator1> & lhs, const ::racecar_cone_msgs::ConePair_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace racecar_cone_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::racecar_cone_msgs::ConePair_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::racecar_cone_msgs::ConePair_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::racecar_cone_msgs::ConePair_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::racecar_cone_msgs::ConePair_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::racecar_cone_msgs::ConePair_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::racecar_cone_msgs::ConePair_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::racecar_cone_msgs::ConePair_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e86328cf0c5c9f6e1d43796e78dbb005";
  }

  static const char* value(const ::racecar_cone_msgs::ConePair_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe86328cf0c5c9f6eULL;
  static const uint64_t static_value2 = 0x1d43796e78dbb005ULL;
};

template<class ContainerAllocator>
struct DataType< ::racecar_cone_msgs::ConePair_<ContainerAllocator> >
{
  static const char* value()
  {
    return "racecar_cone_msgs/ConePair";
  }

  static const char* value(const ::racecar_cone_msgs::ConePair_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::racecar_cone_msgs::ConePair_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"racecar_cone_msgs/Cone left\n"
"racecar_cone_msgs/Cone right\n"
"geometry_msgs/Point midpoint\n"
"float32 width                   # ||right - left||\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: racecar_cone_msgs/Cone\n"
"# Detección de un cono (frame fijo: odom/map)\n"
"std_msgs/Header header\n"
"geometry_msgs/Point p           # posición (z=0 si 2D)\n"
"# Covarianza plana 2x2 (x,y) aplanada (row-major): [xx, xy, yx, yy]\n"
"float32[4] cov_xy\n"
"\n"
"# Lateralidad\n"
"uint8 UNKNOWN=0\n"
"uint8 LEFT=1\n"
"uint8 RIGHT=2\n"
"uint8 side\n"
"\n"
"float32 confidence              # [0..1]\n"
"string source                   # \"lidar\", \"sim\", etc.\n"
"int32 id                        # opcional (tracking)\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::racecar_cone_msgs::ConePair_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::racecar_cone_msgs::ConePair_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left);
      stream.next(m.right);
      stream.next(m.midpoint);
      stream.next(m.width);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConePair_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::racecar_cone_msgs::ConePair_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::racecar_cone_msgs::ConePair_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left: ";
    s << std::endl;
    Printer< ::racecar_cone_msgs::Cone_<ContainerAllocator> >::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    s << std::endl;
    Printer< ::racecar_cone_msgs::Cone_<ContainerAllocator> >::stream(s, indent + "  ", v.right);
    s << indent << "midpoint: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.midpoint);
    s << indent << "width: ";
    Printer<float>::stream(s, indent + "  ", v.width);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RACECAR_CONE_MSGS_MESSAGE_CONEPAIR_H
