// Generated by gencpp from file racecar_cone_msgs/MidpointArray.msg
// DO NOT EDIT!


#ifndef RACECAR_CONE_MSGS_MESSAGE_MIDPOINTARRAY_H
#define RACECAR_CONE_MSGS_MESSAGE_MIDPOINTARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>

namespace racecar_cone_msgs
{
template <class ContainerAllocator>
struct MidpointArray_
{
  typedef MidpointArray_<ContainerAllocator> Type;

  MidpointArray_()
    : header()
    , points()
    , width()
    , cov_xy_flat()
    , id()
    , confidence()  {
    }
  MidpointArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , points(_alloc)
    , width(_alloc)
    , cov_xy_flat(_alloc)
    , id(_alloc)
    , confidence(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _points_type;
  _points_type points;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _width_type;
  _width_type width;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _cov_xy_flat_type;
  _cov_xy_flat_type cov_xy_flat;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _id_type;
  _id_type id;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _confidence_type;
  _confidence_type confidence;





  typedef boost::shared_ptr< ::racecar_cone_msgs::MidpointArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::racecar_cone_msgs::MidpointArray_<ContainerAllocator> const> ConstPtr;

}; // struct MidpointArray_

typedef ::racecar_cone_msgs::MidpointArray_<std::allocator<void> > MidpointArray;

typedef boost::shared_ptr< ::racecar_cone_msgs::MidpointArray > MidpointArrayPtr;
typedef boost::shared_ptr< ::racecar_cone_msgs::MidpointArray const> MidpointArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::racecar_cone_msgs::MidpointArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::racecar_cone_msgs::MidpointArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::racecar_cone_msgs::MidpointArray_<ContainerAllocator1> & lhs, const ::racecar_cone_msgs::MidpointArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.points == rhs.points &&
    lhs.width == rhs.width &&
    lhs.cov_xy_flat == rhs.cov_xy_flat &&
    lhs.id == rhs.id &&
    lhs.confidence == rhs.confidence;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::racecar_cone_msgs::MidpointArray_<ContainerAllocator1> & lhs, const ::racecar_cone_msgs::MidpointArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace racecar_cone_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::racecar_cone_msgs::MidpointArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::racecar_cone_msgs::MidpointArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::racecar_cone_msgs::MidpointArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::racecar_cone_msgs::MidpointArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::racecar_cone_msgs::MidpointArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::racecar_cone_msgs::MidpointArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::racecar_cone_msgs::MidpointArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b6b5155c16724caf7952716fccf9a8ba";
  }

  static const char* value(const ::racecar_cone_msgs::MidpointArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb6b5155c16724cafULL;
  static const uint64_t static_value2 = 0x7952716fccf9a8baULL;
};

template<class ContainerAllocator>
struct DataType< ::racecar_cone_msgs::MidpointArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "racecar_cone_msgs/MidpointArray";
  }

  static const char* value(const ::racecar_cone_msgs::MidpointArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::racecar_cone_msgs::MidpointArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"# Puntos medios ordenados por avance\n"
"geometry_msgs/Point[] points\n"
"\n"
"# Ancho local asociado a cada punto (m)\n"
"float32[] width\n"
"\n"
"# Covarianza 2x2 de cada midpoint, aplanada (row-major) en bloques de 4:\n"
"# [xx, xy, yx, yy,  xx, xy, yx, yy, ...]  => longitud = 4 * N\n"
"float32[] cov_xy_flat\n"
"\n"
"# IDs y confianza opcionales\n"
"int32[] id\n"
"float32[] confidence\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::racecar_cone_msgs::MidpointArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::racecar_cone_msgs::MidpointArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.points);
      stream.next(m.width);
      stream.next(m.cov_xy_flat);
      stream.next(m.id);
      stream.next(m.confidence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MidpointArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::racecar_cone_msgs::MidpointArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::racecar_cone_msgs::MidpointArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
    s << indent << "width[]" << std::endl;
    for (size_t i = 0; i < v.width.size(); ++i)
    {
      s << indent << "  width[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.width[i]);
    }
    s << indent << "cov_xy_flat[]" << std::endl;
    for (size_t i = 0; i < v.cov_xy_flat.size(); ++i)
    {
      s << indent << "  cov_xy_flat[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.cov_xy_flat[i]);
    }
    s << indent << "id[]" << std::endl;
    for (size_t i = 0; i < v.id.size(); ++i)
    {
      s << indent << "  id[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.id[i]);
    }
    s << indent << "confidence[]" << std::endl;
    for (size_t i = 0; i < v.confidence.size(); ++i)
    {
      s << indent << "  confidence[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.confidence[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RACECAR_CONE_MSGS_MESSAGE_MIDPOINTARRAY_H
