// Generated by gencpp from file racecar_cone_msgs/TrackMetrics.msg
// DO NOT EDIT!


#ifndef RACECAR_CONE_MSGS_MESSAGE_TRACKMETRICS_H
#define RACECAR_CONE_MSGS_MESSAGE_TRACKMETRICS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace racecar_cone_msgs
{
template <class ContainerAllocator>
struct TrackMetrics_
{
  typedef TrackMetrics_<ContainerAllocator> Type;

  TrackMetrics_()
    : header()
    , coverage(0.0)
    , std_width(0.0)
    , max_kappa(0.0)
    , integral_kappa_sq(0.0)
    , latency_ms(0.0)
    , cones_raw_count(0)
    , pairs_count(0)
    , midpoints_count(0)
    , notes()  {
    }
  TrackMetrics_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , coverage(0.0)
    , std_width(0.0)
    , max_kappa(0.0)
    , integral_kappa_sq(0.0)
    , latency_ms(0.0)
    , cones_raw_count(0)
    , pairs_count(0)
    , midpoints_count(0)
    , notes(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _coverage_type;
  _coverage_type coverage;

   typedef float _std_width_type;
  _std_width_type std_width;

   typedef float _max_kappa_type;
  _max_kappa_type max_kappa;

   typedef float _integral_kappa_sq_type;
  _integral_kappa_sq_type integral_kappa_sq;

   typedef float _latency_ms_type;
  _latency_ms_type latency_ms;

   typedef uint32_t _cones_raw_count_type;
  _cones_raw_count_type cones_raw_count;

   typedef uint32_t _pairs_count_type;
  _pairs_count_type pairs_count;

   typedef uint32_t _midpoints_count_type;
  _midpoints_count_type midpoints_count;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _notes_type;
  _notes_type notes;





  typedef boost::shared_ptr< ::racecar_cone_msgs::TrackMetrics_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::racecar_cone_msgs::TrackMetrics_<ContainerAllocator> const> ConstPtr;

}; // struct TrackMetrics_

typedef ::racecar_cone_msgs::TrackMetrics_<std::allocator<void> > TrackMetrics;

typedef boost::shared_ptr< ::racecar_cone_msgs::TrackMetrics > TrackMetricsPtr;
typedef boost::shared_ptr< ::racecar_cone_msgs::TrackMetrics const> TrackMetricsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::racecar_cone_msgs::TrackMetrics_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::racecar_cone_msgs::TrackMetrics_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::racecar_cone_msgs::TrackMetrics_<ContainerAllocator1> & lhs, const ::racecar_cone_msgs::TrackMetrics_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.coverage == rhs.coverage &&
    lhs.std_width == rhs.std_width &&
    lhs.max_kappa == rhs.max_kappa &&
    lhs.integral_kappa_sq == rhs.integral_kappa_sq &&
    lhs.latency_ms == rhs.latency_ms &&
    lhs.cones_raw_count == rhs.cones_raw_count &&
    lhs.pairs_count == rhs.pairs_count &&
    lhs.midpoints_count == rhs.midpoints_count &&
    lhs.notes == rhs.notes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::racecar_cone_msgs::TrackMetrics_<ContainerAllocator1> & lhs, const ::racecar_cone_msgs::TrackMetrics_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace racecar_cone_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::racecar_cone_msgs::TrackMetrics_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::racecar_cone_msgs::TrackMetrics_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::racecar_cone_msgs::TrackMetrics_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::racecar_cone_msgs::TrackMetrics_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::racecar_cone_msgs::TrackMetrics_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::racecar_cone_msgs::TrackMetrics_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::racecar_cone_msgs::TrackMetrics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9f81acf08fbcb042f5be8a05aaee3bf6";
  }

  static const char* value(const ::racecar_cone_msgs::TrackMetrics_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9f81acf08fbcb042ULL;
  static const uint64_t static_value2 = 0xf5be8a05aaee3bf6ULL;
};

template<class ContainerAllocator>
struct DataType< ::racecar_cone_msgs::TrackMetrics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "racecar_cone_msgs/TrackMetrics";
  }

  static const char* value(const ::racecar_cone_msgs::TrackMetrics_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::racecar_cone_msgs::TrackMetrics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"# Cobertura de emparejado (0..1)\n"
"float32 coverage\n"
"\n"
"# Estadística de anchos\n"
"float32 std_width                      # desviación estándar de width (m)\n"
"\n"
"# Curvatura y suavidad\n"
"float32 max_kappa                      # max |kappa| (1/m)\n"
"float32 integral_kappa_sq              # ∫ kappa^2 ds (1/m)\n"
"\n"
"# Rendimiento\n"
"float32 latency_ms                     # latencia media del ciclo (ms)\n"
"\n"
"# Contadores\n"
"uint32 cones_raw_count\n"
"uint32 pairs_count\n"
"uint32 midpoints_count\n"
"\n"
"# Notas/diagnóstico\n"
"string notes\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::racecar_cone_msgs::TrackMetrics_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::racecar_cone_msgs::TrackMetrics_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.coverage);
      stream.next(m.std_width);
      stream.next(m.max_kappa);
      stream.next(m.integral_kappa_sq);
      stream.next(m.latency_ms);
      stream.next(m.cones_raw_count);
      stream.next(m.pairs_count);
      stream.next(m.midpoints_count);
      stream.next(m.notes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrackMetrics_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::racecar_cone_msgs::TrackMetrics_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::racecar_cone_msgs::TrackMetrics_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "coverage: ";
    Printer<float>::stream(s, indent + "  ", v.coverage);
    s << indent << "std_width: ";
    Printer<float>::stream(s, indent + "  ", v.std_width);
    s << indent << "max_kappa: ";
    Printer<float>::stream(s, indent + "  ", v.max_kappa);
    s << indent << "integral_kappa_sq: ";
    Printer<float>::stream(s, indent + "  ", v.integral_kappa_sq);
    s << indent << "latency_ms: ";
    Printer<float>::stream(s, indent + "  ", v.latency_ms);
    s << indent << "cones_raw_count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.cones_raw_count);
    s << indent << "pairs_count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.pairs_count);
    s << indent << "midpoints_count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.midpoints_count);
    s << indent << "notes: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.notes);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RACECAR_CONE_MSGS_MESSAGE_TRACKMETRICS_H
